<?php

namespace Balt\LaravelIconCaptcha;

use Illuminate\Support\ServiceProvider;

class IconCaptchaServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(): void
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/licRoutes.php');

        //TODO: Translation files einbauen
        $this->loadTranslationsFrom(__DIR__.'/assets/lang', 'laravel-icon-captcha');

        //Publish Funktion
        $this->publishes([
            __DIR__ . '/assets/js' =>
                resource_path('assets/vendor/laravel-icon-captcha/js'
                ),
            __DIR__ . '/assets/svg' =>
                public_path('assets/vendor/laravel-icon-captcha/svg'
                ),
            __DIR__ . '/assets/css' =>
                resource_path('assets/vendor/laravel-icon-captcha/css'
                )
        ]);
    }
}
